### ISSUE TITLE
Time for a stable tag?

### ISSUE THREAD

**Issue by ruudk** [itavero/AMNL-Mollie#15]
I think it's stable enough! Just release a 1.0.0 version :)

**Comment by ruudk** [comment]
The reason for this is that I want to set `minimum-stability` to `stable`. When I include my `ruudk/mollie-bundle` it complains that it will not instal `v0.0.1-RC03` of your bundle.

**Comment by itavero** [comment]
I'll tag it in a bit.

**Comment by itavero** [comment]
@ruudk The version tag [has been added](https://packagist.org/packages/amnl/mollie#v1.0.0)! :wink: 

PS: I'm planning on doing running some static code analysis tools in the next few months, so I can try to improve the overall code quality of the library.

**Comment by ruudk** [comment]
Cool, thanks!
