### ISSUE TITLE
Cancelled transaction will turn to 'paid' when checking status twice

### ISSUE THREAD

**Issue by jelrikvh** [itavero/AMNL-Mollie#17]
Hi,

I read the following note in your documentation:

```
Important note: If a transaction had the status "paid" (paid == true) and you request the status a second time,
paid will still be true. This behaviour is different from the default implementation that Mollie uses. However, 
you can check the status property (which contains the message received from the API) to see if you have 
checked the transaction status before.
```

In the code (https://github.com/itavero/AMNL-Mollie/blob/master/lib/AMNL/Mollie/IDeal/IDealTransactionStatus.php#L44) I see that the `$paid === false` is transformed into a `true`. The note in the documentation is true, but the code ALSO turns, for example, `Cancelled` transactions to `paid=true`.

The problem is: this also happens when the payment has been cancelled. This way, you might well end up with marking a payment as 'paid' while it is not. I think this is a bug of major importance, but I might be wrong. Please do not hesitate to explain why the behaviour makes sense :-).

_Reproduction_
1. Initiate a transaction.
2. Visit the payment URL.
3. Make the payment fail (in test mode: click the big red button)
4. Check the status of the transaction (which is `Cancelled`, with `paid=false`)
5. Check the status of the transaction again (which is `CheckedBefore`, with `paid=true`!)

Regards,
Jelrik van Hal

**Comment by itavero** [comment]
I wasn't aware of the fact that the status would turn in to `CheckedBefore` regardless of the previous state.
I assumed it would only do that when the status was `Success` the first time.
For now, I'll comment out that code and contact Mollie to verify the behavior of the iDEAL API.

PS: Sorry for the late reply due to my vacation :wink:

**Comment by itavero** [comment]
@jelrikvh I've sent an email to Mollie to clarify the behavior.
Depending on there response I will adjust the code further to work properly with their API (this will mean either removing this functionality and just keeping the corky response from Mollie or adjusting it so it knows when and how to "fix" the response).
After that I'll create a new tag, so for now you should use `dev-master` if you are using Composer to manage your dependencies and want to avoid this bug.

**Comment by itavero** [comment]
Added a branch alias to composer.json so you can just change the minimum stability level or use `"amnl/mollie": "1.0.*@dev"` in your composer.json

**Comment by itavero** [comment]
Received a reply from Mollie (in Dutch):

> CheckedBefore geven we terug bij een success status die al eens is opgevraagd. Bij een failure geven we dit uiteraard niet. Een latere check is dus voor een success betaling niet mogelijk. Mocht u nog vragen hebben dan hoor ik dat natuurlijk graag.

That means that the code was behaving as it should.

@jelrikvh Can you please test it again, just to be sure, using the stable release (1.0.0)?

**Comment by itavero** [comment]
Received another reply from Mollie: apparently you are right. Their API only allows you to check if a payment was successful the first time. After that it will always return false.

I'll remove the code and update the docs asap.

**Comment by itavero** [comment]
I have removed the code and the documentation site is being regenerated right now.
Thanks for the bug report, @jelrikvh! :+1:

**Comment by jelrikvh** [comment]
Sorry for my late reply due to a vacation of my own ;-).
Did you get any lead from Mollie if they will change the weird behaviour of their API?

**Comment by itavero** [comment]
Haven't spoken about that with them, but I reckon it's unlikely they will.

**Comment by jelrikvh** [comment]
Pity. Thanks anyway!
