### ISSUE TITLE
Creditcard API

### ISSUE THREAD

**Issue by ruudk** [itavero/AMNL-Mollie#20]
I'll start working on this in a couple of weeks.

https://www.mollie.nl/beheer/betaaldiensten/creditcard/documentatie

**Comment by itavero** [comment]
Nice. Didn't even know they had a new payment method.
I'll review your code when it's available :wink:

**Comment by itavero** [comment]
@ruudk Have you seen the new Mollie API?
Perhaps it's a better idea to see if we can implement that or use their library?

**Comment by ruudk** [comment]
Haven't had time to look into it as we don't need it right now. But I'm thinking it would be better to use https://github.com/omnipay/omnipay instead. It has lots of services built-in.
