### ISSUE TITLE
Add documentation and examples

### ISSUE THREAD

**Issue by itavero** [itavero/AMNL-Mollie#3]
This library still needs some documentation.
I think the best approach would be to write it similar to the official Mollie documentation.
That way people can easily see how things were done using the library Mollie is providing and how it is done when using this library.

The documentation should either be on the wiki or on GitHub Pages.
I think I prefer the latter, but both need to be activated before they can be used.
Hopefully I'll find some spare time soon, to fix this.

**Comment by ruudk** [comment]
Why not simply put it in the readme file?

**Comment by itavero** [comment]
That could be an option as well, but I was thinking of providing some examples for each payment method.
If I would put that in the README, I'm afraid it will be too much information on a single page.

**Comment by itavero** [comment]
Some documentation is now available at http://itavero.github.io/AMNL-Mollie/
It's not very elaborate, but I guess it will suffice for now.
