### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by ruudk** [itavero/AMNL-Mollie#5]
Add some basic unit tests. That would have prevented bug #4 :)

**Comment by itavero** [comment]
If I had designed a test for using other Buzz clients it would have prevented #4 indeed. :tongue: 
I'm currently very busy doing all kinds of stuff non-PHP so it might take a while before I get to this, but everyone is more than welcome to submit pull requests.

Note that you should probably create a mock-client in that case, to make sure the unit tests work even when there are some internet issues or issues at Mollie.
I find that it's never a great idea to depend on a web service in the unit tests (besides, it would require an active Mollie account too).

**Comment by itavero** [comment]
I've added a seperate branch (`unit-tests`) to start working on the tests.
When they are finished, I think it would be nice to setup something like Travis CI as well.

**Comment by itavero** [comment]
A way to mock the response can be found here:
https://github.com/lyrixx/Series/blob/master/Series/Tests/Provider/Upstream/DailyTvTorrentProviderTest.php
(Thanks to @lyrixx.)

**Comment by lyrixx** [comment]
@itavero You're welcome ;)

**Comment by itavero** [comment]
I hope to add unit tests for the actual gateways soon.

**Comment by itavero** [comment]
Still need to write some unit tests that test the requests that are being generated by the Gateway classes.

**Comment by itavero** [comment]
Unit tests are pretty much done now, I guess.
Any comments, @ruudk?

**Comment by ruudk** [comment]
Awesome! Thanks :)
